"""
Django settings for realestate project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔐 SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-_lvzgb#^$!hbcqyv8on$lua$$%1h($uugz_1!v1_wr3s0$d)1)')

# ⚙️ Debug Mode (Set False in live render if possible)
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# 🌍 Allowed hosts ✔ (No http/https prefix allowed)
ALLOWED_HOSTS = [
    "realestate-chatbot-backend-czom.onrender.com",  # Backend (Render)
    "localhost",
    "127.0.0.1"
]

# ✔ Installed apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

# 🌎 CORS settings → allow your frontend (Vercel)
CORS_ALLOWED_ORIGINS = [
    "https://realestate-chatbot-frontend.vercel.app",  # Frontend live
    "http://localhost:5173"  # React local dev
]

# ❗ Temporary (optional) — remove once working
# CORS_ALLOW_ALL_ORIGINS = True  

# 🧵 Middleware
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'realestate.urls'

# 🎨 Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 🔥 WSGI Entry
WSGI_APPLICATION = 'realestate.wsgi.application'

# 🗃 SQLite DB
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 🔑 Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🌐 Language & Time
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# 📦 Static files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"  # For deployment

# 🔢 Default Field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
