"""
Django settings for realestate project.
Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent

# 🔐 SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-_lvzgb#^$!hbcqyv8on$lua$$%1h($uugz_1!v1_wr3s0$d)1)')

# ⚙️ Debug Mode (True for development, False in production)
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# 🌍 Allowed hosts (NO http:// or https:// here)
ALLOWED_HOSTS = [
    "realestate-chatbot-backend-czom.onrender.com",  # Backend (Render)
    "realestate-chatbot-frontend.vercel.app",        # Frontend (Vercel)
    "localhost",
    "127.0.0.1",
]

# ✔ Installed apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

# 🌎 CORS settings (allows frontend to access backend)
CORS_ALLOWED_ORIGINS = [
    "https://realestate-chatbot-frontend.vercel.app",  # Live frontend
    "http://localhost:5173",  # Local dev frontend
]

# 🛑 Temporary override to allow all origins (remove after testing)
CORS_ALLOW_ALL_ORIGINS = True

# 🧵 Middleware
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# URL Configuration
ROOT_URLCONF = 'realestate.urls'

# 🎨 Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 🔥 WSGI Entry
WSGI_APPLICATION = 'realestate.wsgi.application'

# 🗃 Database (SQLite)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# 🔑 Password Validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# 🌐 Language & Timezone
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# 📦 Static files
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"  # Required for Render Deployment

# 🔢 Default Field Type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
